# Generated by Django 2.1.2 on 2018-12-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_details',
            name='Request_Number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='Request_Status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='Sub_Request_Number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='Sub_Request_Status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
